# Generated by Django 4.1.13 on 2024-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgranttable',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='accessgranttable',
            name='given_date',
            field=models.DateTimeField(),
        ),
    ]
