# Generated by Django 4.2 on 2024-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_accessgranttable_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgranttable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
