---
- name: Revoke Access
  hosts: all
  become: yes
  vars:
    - filename: user
      domain: domain
      
  vars_files:
    - vars.yml
  tasks:      
    - name: Remove user from sudoers file
      lineinfile:
        path: "/access_control/access_grant/ansible/test"       
        regexp: '^{{ item }}'
        state: absent
      loop: "{{ usernames }}"

    - name: Stop & Start sssd
      ansible.builtin.service:
        name: sssd
        state: restarted
        enabled: true
      ignore_errors: true
